order impl
artemsa223/book-shop pull request #16
Opened 2024-03-20 23:45 UTC by artemsa223

2024-03-21 17:59 UTC, Vasul-Pankiv requested changes

2024-03-21 17:59 UTC, Vasul-Pankiv commented on src/main/java/com/example/demo/controller/OrderController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
it is not necessary to check for USER role if you have only USER and ADMIN roles

2024-03-21 17:59 UTC, Vasul-Pankiv commented on src/main/java/com/example/demo/mapper/CartItemMapper.java
> +
remove empty line

2024-03-21 17:59 UTC, Vasul-Pankiv commented on src/main/java/com/example/demo/mapper/ShoppingCartMapper.java
> +
empty line

2024-03-21 17:59 UTC, Vasul-Pankiv commented on src/main/java/com/example/demo/service/shoppingcart/ShoppingCartServiceImpl.java
> +
why you need this method, use getCartByUserId directly, It is 2 identical methods but better to use getShoppingCartByUserId name

2024-03-21 17:59 UTC, Vasul-Pankiv commented on src/main/java/com/example/demo/service/order/OrderServiceImpl.java
> +        order = orderRepository.save(order);
why are you saving an order here, it is redundant

2024-03-21 17:59 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/changes/16-insert-cartitems.yaml
> +                  value: "3"
File should end with empty line

2024-03-22 12:34 UTC, kerrrusha approved these changes
looks good

2024-03-22 18:08 UTC, merged