implementation spring data jpa
artemsa223/book-shop pull request #5
Opened 2024-02-27 09:54 UTC by artemsa223

2024-02-27 12:04 UTC, Vasul-Pankiv requested changes

2024-02-27 12:04 UTC, Vasul-Pankiv commented on src/main/java/com/example/demo/service/BookServiceImpl.java
> +                    return bookRepository.save(book);
use mapper to convert requestDto to model

2024-02-27 12:04 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  nullable: false
file should end with empty line

2024-02-27 12:04 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
file should end with empty line

2024-02-28 09:36 UTC, Rommelua requested changes

2024-02-28 09:36 UTC, Rommelua commented on src/main/java/com/example/demo/controller/BookController.java
> +    }
remove this end point
![image](https://github.com/artemsa223/book-shop/assets/20326858/9f3e0b55-b0aa-4f82-9fda-3f8cf655c741)

2024-02-28 09:36 UTC, Rommelua commented on src/main/java/com/example/demo/repository/BookRepository.java
> +    List<Book> findAllByTitleContainsIgnoreCase(String title);
remove this method

2024-02-28 09:36 UTC, Rommelua commented on src/main/java/com/example/demo/service/BookService.java
> +    List<BookDto> findAllByTitle(String title);
remove this method

2024-02-28 12:09 UTC, okuzan approved these changes
Well done

2024-02-28 12:09 UTC, okuzan commented on src/main/java/com/example/demo/model/Book.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```

2024-02-28 12:55 UTC, merged